project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "!materials/"
  execute-dir: project

website:
  title: "LLMs in R for Data Analysis"
  navbar:
    background: dark
    right:
      - icon: file-certificate
        href: license-web.qmd
      - icon: github
        href: https://github.com/thisisnic/rainbowr-workshop
        text: GitHub

    left:
      - href: index.qmd
        text: Home
      - text: Code
        href: code.qmd

format:
  html:
    theme: cosmo
    css: styles.scss
    toc: true
    link-external-newwindow: true

editor: source
engine: knitr
execute:
  freeze: auto
